version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: surveyapp-db
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: survey
      POSTGRES_PASSWORD: survey123
      POSTGRES_DB: surveydb
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: surveyapp-api
    ports:
      - "5454:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  pgdata:
