version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/windows/servercore:ltsc2019
    environment:
      SA_PASSWORD: "Your_strong(!)Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: Dockerfile.windows
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
volumes: {}
